### ISSUE TITLE
Constants from lexical variables potentially modified elsewhere are deprecated

### ISSUE THREAD

**Issue by eserte** [xslate/p5-Text-Xslate#135]
perl 5.21.7 has a new warning which is causing the test suite to fail. See http://www.cpantesters.org/cpan/report/57d24bca-88c4-11e4-b194-8c305ef060ad for a sample fail report.

**Comment by miyagawa** [comment]
This change was added in perl 5.21.6.
http://search.cpan.org/~bingos/perl-5.21.6/pod/perldelta.pod#Inlining_of_sub_()_{_$var_}_with_observable_side-effects

@eserte it looks like you created a bunch of bug reports on this specific warning (because googling this message shows them). I recommend you to put the correct link to the warnings and changelog entry so that the author can figure out what is the right thing to do - whether to fix the code to not depend on the lexical var, or turn off warnings because that's what the code tries to do.
